name: Build naruzhu APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Download project
        run: |
          wget -O project.zip https://github.com/ermolovartem76-art/Hjjjk/releases/download/Ggg/naruzhu_app_updated-3.zip
          mkdir -p godot_project
          unzip -o project.zip -d godot_project

      - name: Setup android
        uses: android-actions/setup-android@v3

      - name: export game
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.7.1/Godot_v4.7.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.7.1/Godot_v4.7.1-stable_export_templates.tpz
          relative_project_path: ./godot_project/naruzhu_app_updated-3/naruzhu_app_updated/naruzhu_app
          archive_output: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: naruzhu-apk
          path: ${{ steps.export.outputs.build_directory }}
